name: Java CI com Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar projeto
        run: mvn clean compile

      - name: Executar testes
        run: mvn test

      - name: Deploy simulado
        if: github.ref == 'refs/heads/main'
        run: echo "Deploy realizado com sucesso!"