name: Pipeline com Maven em Java

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar projeto
        run: mvn -B clean compile

      - name: Fazer Testes
        run: mvn -B test

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: echo "Deploy concluido"